### PR TITLE
ghost: support marathons

### PR DESCRIPTION
**Pull request by matthewearl**
Fixes https://github.com/j0zzz/JoeQuake/issues/63

Still needs a bit more testing, but I've tried it out with [Muty's 12:11 id1](https://www.speedrun.com/quake/run/ylq0vk3z). On my machine loading `end` with the ghost enabled is apparently instant, which should be the slowest map to load since it has to go through the entire demo.

### CODE REVIEW

**Comment by matthewearl** [comment]
I've added a new commit which adds support for multi-demo marathons chained with a stuff_text "playdemo".  Updated the PR title to reflect this.

**Comment by matthewearl** [comment]
There's a merge conflict on this branch with https://github.com/j0zzz/JoeQuake/pull/60 relating to whether `Ghost_ReadDemo` takes a `char *` or a `FILE *`, I'll sort it out when the time comes.

**Comment by matthewearl** [comment]
I've fixed the conflicts.  Separate to that, there's a slight annoyance with the `marathon` command in that when you playback a demo recorded with version of JQ on an older joequake (or not joequake at all) then you get an "unknown command: marathon" message at the start of each level.  I could instead hack some other command to hide it entirely?  For example, I could encode it in the [`looptrack` argument of `svc_cdtrack`](https://github.com/j0zzz/JoeQuake/blob/master/trunk/cl_parse.c#L1467) which as far as I can tell has always been ignored. Thoughts?

**Comment by matthewearl** [comment]
In fact, if I use an `svc_print` in the server info packet it doesn't appear on the screen, just when you pull down the console.  I should be able to eliminate the message on marathon start too, just requiring a message for marathon continuation.  So this would just be a `svc_print` with a message like "Continuing JoeQuake marathon", which would be less alarming than an "unknown command" error on the screen on every map load, but that can still be parsed programmatically.  Also less hacky than the `svc_cdtrack` solution.

**Comment by j0zzz** [comment]
Yeah, I like the solution using the svc_print server command. Putting into the svc_cdtrack seemed like a nasty hack to me either.

**Pull request merged**
